/**
 * reportScheduler.ts
 * Cron-based scheduler for automated report generation and delivery.
 * In production: replace S3 stub with actual AWS SDK / Cloudflare R2 calls.
 */

import { connectDB } from "@/lib/db";
import { ScheduledReport, ReportLog, REPORT_STATUS } from "@/models/ReportLog";
import { generateCustomReport } from "./reportGenerators";
import { randomBytes } from "crypto";

/* --- Types -------------------------------------------------------------------- */
export interface ScheduleConfig {
  templateKey: string;
  title:       string;
  frequency:   "DAILY" | "WEEKLY" | "MONTHLY";
  recipients:  string[];
  createdBy:   string;
}

/* --- Helpers ------------------------------------------------------------------ */
function generateReportId(): string {
  return `RPT-${Date.now().toString(36).toUpperCase()}-${randomBytes(2).toString("hex").toUpperCase()}`;
}

function nextRunDate(frequency: "DAILY" | "WEEKLY" | "MONTHLY"): Date {
  const d = new Date();
  if (frequency === "DAILY")   d.setDate(d.getDate() + 1);
  if (frequency === "WEEKLY")  d.setDate(d.getDate() + 7);
  if (frequency === "MONTHLY") d.setMonth(d.getMonth() + 1);
  d.setHours(6, 0, 0, 0); // 6 AM BST
  return d;
}

/* --- uploadToStorage ---------------------------------------------------------- */
async function uploadToStorage(buffer: Buffer, filename: string): Promise<string> {
  // TODO: Replace with actual S3/R2 upload
  // const s3 = new S3Client({ region: process.env.AWS_REGION });
  // await s3.send(new PutObjectCommand({ Bucket: process.env.S3_BUCKET, Key: filename, Body: buffer }));
  // return `https://${process.env.S3_BUCKET}.s3.amazonaws.com/${filename}`;

  // Stub: return a placeholder URL
  console.info("[reportScheduler] uploadToStorage stub:", filename, `${buffer.length} bytes`);
  return `https://storage.vax.gov.bd/reports/${filename}`;
}

/* --- sendReportEmail ---------------------------------------------------------- */
async function sendReportEmail(recipients: string[], title: string, downloadUrl: string): Promise<void> {
  const apiKey = process.env.SENDGRID_API_KEY;
  if (!apiKey) {
    console.warn("[reportScheduler] SendGrid not configured - email skipped");
    return;
  }

  const html = `
    <h2>VaxAdmin Report Ready</h2>
    <p>Your scheduled report <strong>${title}</strong> has been generated.</p>
    <p><a href="${downloadUrl}" style="background:#10B981;color:white;padding:10px 20px;border-radius:6px;text-decoration:none;">Download Report</a></p>
    <p style="color:#6B7280;font-size:12px;">Link expires in 7 days. Generated by VaxAdmin Reporting System.</p>
  `;

  await fetch("https://api.sendgrid.com/v3/mail/send", {
    method:  "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
    body: JSON.stringify({
      personalizations: recipients.map((email) => ({ to: [{ email }] })),
      from:    { email: process.env.SMTP_FROM ?? "reports@vax.gov.bd", name: "VaxAdmin Reports" },
      subject: `[VaxAdmin] ${title} - Ready for Download`,
      content: [{ type: "text/html", value: html }],
    }),
  }).catch((e) => console.error("[reportScheduler] Email send failed:", e));
}

/* --- runScheduledReport ------------------------------------------------------- */
export async function runScheduledReport(scheduleId: string): Promise<void> {
  await connectDB();

  const schedule = await ScheduledReport.findOne({ scheduleId });
  if (!schedule || !schedule.isActive) return;

  const reportId = generateReportId();

  const log = await ReportLog.create({
    reportId,
    type:        schedule.templateKey,
    title:       schedule.title,
    format:      "PDF",
    status:      REPORT_STATUS.GENERATING,
    generatedBy: schedule.createdBy,
    config:      { templateKey: schedule.templateKey },
  });

  try {
    const buffer = await generateCustomReport({
      type:    schedule.templateKey,
      title:   schedule.title,
      format:  "PDF",
      metrics: ["vaccinations", "coverage", "supply", "fraud"],
    });

    const filename   = `${reportId}-${schedule.templateKey}.pdf`;
    const fileUrl    = await uploadToStorage(buffer, filename);

    log.status   = REPORT_STATUS.READY;
    log.fileUrl  = fileUrl;
    log.fileSize = buffer.length;
    await log.save();

    await sendReportEmail(schedule.recipients, schedule.title, fileUrl);

    schedule.lastRunAt = new Date();
    schedule.nextRunAt = nextRunDate(schedule.frequency);
    await schedule.save();
  } catch (e) {
    log.status   = REPORT_STATUS.FAILED;
    log.errorMsg = String(e);
    await log.save();
    console.error("[reportScheduler] Report generation failed:", e);
  }
}

/* --- initScheduler ------------------------------------------------------------ */
/**
 * Call this once at app startup (e.g. in a Next.js instrumentation.ts file).
 * Uses node-cron to check for due scheduled reports every minute.
 */
export async function initScheduler(): Promise<void> {
  try {
    const cron = await import("node-cron");

    // Every minute: check for due reports
    cron.schedule("* * * * *", async () => {
      await connectDB();
      const due = await ScheduledReport.find({
        isActive:  true,
        nextRunAt: { $lte: new Date() },
      }).lean();

      for (const s of due) {
        runScheduledReport(s.scheduleId).catch((e) =>
          console.error("[reportScheduler] Failed to run:", s.scheduleId, e)
        );
      }
    });

    console.info("[reportScheduler] Scheduler initialized");
  } catch {
    console.warn("[reportScheduler] node-cron not available - scheduler disabled");
  }
}

/* --- createSchedule ----------------------------------------------------------- */
export async function createSchedule(config: ScheduleConfig): Promise<string> {
  await connectDB();

  const scheduleId = `SCH-${Date.now().toString(36).toUpperCase()}-${randomBytes(2).toString("hex").toUpperCase()}`;

  await ScheduledReport.create({
    scheduleId,
    templateKey: config.templateKey,
    title:       config.title,
    frequency:   config.frequency,
    recipients:  config.recipients,
    isActive:    true,
    createdBy:   config.createdBy,
    nextRunAt:   nextRunDate(config.frequency),
  });

  return scheduleId;
}
